apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-standard
provisioner: nfs.csi.k8s.io
 
parameters:
  server: 172.31.2.141
  share: /var/nfs/general
 
reclaimPolicy: Delete
volumeBindingMode: Immediate